### ISSUE TITLE
File descriptor leak when using Anthropic client 

### ISSUE THREAD

**Issue by deter3** [anthropics/anthropic-sdk-python#128]
I have tested anthropic 0.3.11 and 0.2.9 , both might have File descriptor leak .

code 1 :
```py
@retry(stop=stop_after_attempt(5), wait=wait_exponential(max=10), retry=retry_if_exception_type((ConnectionResetError,anthropic.InternalServerError) ))
def send_something():
	prompt = "\n\nHuman: This is a test prompt. Return some randome text\n\nAssistant":
	client = anthropic.Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])
	resp = client.completions.create(
		prompt=prompt,
		stop_sequences=[anthropic.HUMAN_PROMPT],
		model="claude-instant-1.2",
		max_tokens_to_sample=100,
	)
	client.close()
	return resp.completion

if name == "main":
	client = None
	for i in range(10000):
		print(send_something())
```

code 2 :

```py
@retry(stop=stop_after_attempt(5), wait=wait_exponential(max=10), retry=retry_if_exception_type((ConnectionResetError,anthropic.InternalServerError) ))
def send_something():
	prompt = "\n\nHuman: This is a test prompt. Return some randome text\n\nAssistant:"
	resp = client.completions.create(
		prompt=prompt,
		stop_sequences=[anthropic.HUMAN_PROMPT],
		model="claude-instant-1.2",
		max_tokens_to_sample=100,
	)
	return resp.completion

if name == "main":
	client = anthropic.Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])
	for i in range(10000):
		print(send_something())
```

Both code led to File descriptor leak eventually after 5000-10000 loops . I ever tried to remove the retry and the same File descriptor leak happened . When changed to use

```py
headers = {"x-api-key": f'{api_key}', "Content-Type": 'application/json'} 
data = {"prompt": f'\n\nHuman: {prompt1}\n\nAssistant: ',"model": 'claude-instant-1.2',"max_tokens_to_sample": 10000,"temperature":0} 
r = requests.post('https://api.anthropic.com/v1/complete', headers=headers, json=data,timeout=500)
```

everything is fine . no File descriptor leak at all .

**Comment by rattrayalex** [comment]
Thanks for reporting this. Can you share the file descriptor error message you encountered?

**Comment by rattrayalex** [comment]
Have you tried using the client with a context?

```py
def send_something():
  with anthropic.Anthropic() as client:
    resp = client.completions.create(…)
    return resp.completion
```

**Comment by deter3** [comment]
> Thanks for reporting this. Can you share the file descriptor error message you encountered?

Below is the  file descriptor error message  . Basially what I see is the system memory is running low when the loops keep going , eventually the system memory is getting really low and the process will be killed . 

```
Traceback (most recent call last):
  File "/home/peS2o_paper/script/pub_abstarct2.py", line 317, in <module>
  File "/home/peS2o_paper/script/pub_abstarct2.py", line 194, in claude_making_jokes2
  File "/root/.pyenv/versions/3.9.17/lib/python3.9/site-packages/anthropic/_client.py", line 101, in __init__
  File "/root/.pyenv/versions/3.9.17/lib/python3.9/site-packages/anthropic/_base_client.py", line 674, in __init__
  File "/root/.pyenv/versions/3.9.17/lib/python3.9/site-packages/httpx/_client.py", line 672, in __init__
  File "/root/.pyenv/versions/3.9.17/lib/python3.9/site-packages/httpx/_client.py", line 720, in _init_transport
  File "/root/.pyenv/versions/3.9.17/lib/python3.9/site-packages/httpx/_transports/default.py", line 126, in __init__
  File "/root/.pyenv/versions/3.9.17/lib/python3.9/site-packages/httpx/_config.py", line 52, in create_ssl_context
  File "/root/.pyenv/versions/3.9.17/lib/python3.9/site-packages/httpx/_config.py", line 76, in __init__
  File "/root/.pyenv/versions/3.9.17/lib/python3.9/site-packages/httpx/_config.py", line 88, in load_ssl_context
  File "/root/.pyenv/versions/3.9.17/lib/python3.9/site-packages/httpx/_config.py", line 147, in load_ssl_context_verify
OSError: [Errno 24] Too many open files
Exception ignored in: <function Anthropic.__del__ at 0x7f238c7ed4c0>
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.9.17/lib/python3.9/site-packages/anthropic/_client.py", line 224, in __del__
  File "/root/.pyenv/versions/3.9.17/lib/python3.9/site-packages/anthropic/_base_client.py", line 691, in close
AttributeError: 'Anthropic' object has no attribute '_client'
```

**Comment by deter3** [comment]
> 



> Have you tried using the client with a context?
> 
> ```python
> def send_something():
>   with anthropic.Anthropic() as client:
>     resp = client.completions.create(…)
>     return resp.completion
> ```

Sure , I will try to test it later on . Might 2-3 days later since my code is running now .

**Comment by RobertCraigie** [comment]
Hey @deter3, I can reproduce this issue when instantiating the client in the loop but only when I do not call `.close()`.

For example this works for me:
```py
client = Anthropic(base_url=base_url)

for _ in range(1000):
    prompt = "\n\nHuman: This is a test prompt. Return some randome text\n\nAssistant:"
    client.completions.create(
        prompt=prompt,
        stop_sequences=[anthropic.HUMAN_PROMPT],
        model="claude-instant-1.2",
        max_tokens_to_sample=100,
    )
```

Whereas this does not, I get the same error you shared:
```py
for _ in range(1000):
    prompt = "\n\nHuman: This is a test prompt. Return some randome text\n\nAssistant:"
    client = Anthropic(base_url=base_url)
    client.completions.create(
        prompt=prompt,
        stop_sequences=[anthropic.HUMAN_PROMPT],
        model="claude-instant-1.2",
        max_tokens_to_sample=100,
    )
```

The second example can work if `.close()` is called but I highly recommend avoiding this pattern as it results in a massive performance loss
```py
for _ in range(1000):
    prompt = "\n\nHuman: This is a test prompt. Return some randome text\n\nAssistant:"
    client = Anthropic(base_url=base_url)
    client.completions.create(
        prompt=prompt,
        stop_sequences=[anthropic.HUMAN_PROMPT],
        model="claude-instant-1.2",
        max_tokens_to_sample=100,
    )
    client.close()
```

**Comment by rattrayalex** [comment]
@deter3 any reason not to instantiate the client once per file, rather than once per call?

**Comment by deter3** [comment]
> @deter3 any reason not to instantiate the client once per file, rather than once per call?

Reason is simple , when I had leak problem in instantiating the client once per file , I tried on  once per call to see the result .  With @RobertCraigie test result above , I had different results as stated at the begining : both code 1 and code 2 had leak problem .  I am using Ubuntu 18.04.6 LTS (GNU/Linux 4.15.0-20-generic x86_64) .  I will try to find a time to find out whether the leak problem is randomly happening regardless instantiating the client once per file or once per call  . Will keep you posted .

**Comment by rattrayalex** [comment]
I'm going to assume that calling moving client instantiation out of your loop, and/or calling `client.close()` (perhaps by using `with`) resolved this issue, since it [appears to in our testing](https://github.com/anthropics/anthropic-sdk-python/issues/128#issuecomment-1695311116). 

You're welcome to reopen if the problem is still active with the tools we provide above.
