### ISSUE TITLE
Tokenizer Error

### ISSUE THREAD

**Issue by williambarberjr** [anthropics/anthropic-sdk-python#132]
When I run:
pip install anthropic

Then:

from anthropic import Anthropic

client = Anthropic()
client.count_tokens('Hello world!')  # 3

I get the error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".pyenv\pyenv-win\versions\3.11.3\Lib\site-packages\anthropic\_client.py", line 225, in count_tokens
    tokenizer = self.get_tokenizer()
                ^^^^^^^^^^^^^^^^^^^^
  File ".pyenv\pyenv-win\versions\3.11.3\Lib\site-packages\anthropic\_client.py", line 230, in get_tokenizer
    return sync_get_tokenizer()
           ^^^^^^^^^^^^^^^^^^^^
  File ".pyenv\pyenv-win\versions\3.11.3\Lib\site-packages\anthropic\_tokenizers.py", line 33, in sync_get_tokenizer
    text = tokenizer_path.read_text()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".pyenv\pyenv-win\versions\3.11.3\Lib\pathlib.py", line 1059, in read_text
    return f.read()
           ^^^^^^^^
  File ".pyenv\pyenv-win\versions\3.11.3\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1980: character maps to <undefined>

I'm on a windows machine and setting my environment variables -> system settings PYTHONUTF8 to 1 didn't work either.

**Comment by rattrayalex** [comment]
Thanks for the report @williambarberjr ! We'll take a look at this soon.

**Comment by RobertCraigie** [comment]
@williambarberjr are you sure you're using the latest version of this package? (v0.3.11)

This should be fixed as we explicitly set the encoding but that isn't present in your stack trace. https://github.com/anthropics/anthropic-sdk-python/blob/7b490f7c46abc160bf649bf68ea1b9375a8cef18/src/anthropic/_tokenizers.py#L33

**Comment by dgellow** [comment]
I've been able to replicate the problem when using `anthropic==0.3.1` (and `pydantic<2.0.0`) on a Windows machine where I'm using German as the display language.

```
python .\main.py
Traceback (most recent call last):
  File "C:\Users\sam\Development\stainless\test-anthropic-sdk-python\main.py", line 4, in <module>
    client.count_tokens("hello world")
  File "C:\Users\sam\AppData\Local\Programs\Python\Python310\lib\site-packages\anthropic\_client.py", line 225, in count_tokens
    tokenizer = self.get_tokenizer()
  File "C:\Users\sam\AppData\Local\Programs\Python\Python310\lib\site-packages\anthropic\_client.py", line 230, in get_tokenizer
    return sync_get_tokenizer()
  File "C:\Users\sam\AppData\Local\Programs\Python\Python310\lib\site-packages\anthropic\_tokenizers.py", line 33, in sync_get_tokenizer
    text = tokenizer_path.read_text()
  File "C:\Users\sam\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 1135, in read_text
    return f.read()
  File "C:\Users\sam\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1980: character maps to <undefined>
```

And I can confirm the solution Robert mentioned, updating to `anthropic==0.3.11` fixes the problem.

**Comment by rattrayalex** [comment]
@williambarberjr please reopen if you can confirm the bug persists on `^0.3.11`
