### ISSUE TITLE
Install fails on M1 Mac due to PyYAML errors

### ISSUE THREAD

**Issue by johnsonfarmsus** [anthropics/anthropic-sdk-python#342]
**System Info**:
MacMini M1, macOS 14.2.1, Python 3.11.5

**Steps To Reproduce**:
1. `python3 -m venv claude-env`
2. `pip install claude`

**Full Error Log**:
Collecting claude==0.4.10
  Using cached claude-0.4.10.tar.gz (1.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting aiohttp~=3.5 (from claude==0.4.10)
  Using cached aiohttp-3.9.3.tar.gz (7.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting Jinja2~=2.10 (from claude==0.4.10)
  Using cached Jinja2-2.11.3.tar.gz (257 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting configpp~=0.3 (from claude==0.4.10)
  Using cached configpp-0.5.0.tar.gz (354 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting lxml~=4.4 (from claude==0.4.10)
  Using cached lxml-4.9.4.tar.gz (3.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pymemcache~=2.2 (from claude==0.4.10)
  Using cached pymemcache-2.2.2.tar.gz (41 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting cssselect~=1.1 (from claude==0.4.10)
  Using cached cssselect-1.2.0.tar.gz (41 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting cachetools~=3.1 (from claude==0.4.10)
  Using cached cachetools-3.1.1.tar.gz (22 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pychromecast~=3.2 (from claude==0.4.10)
  Using cached PyChromecast-3.2.3.tar.gz (43 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting aiohttp-middlewares~=1.1 (from claude==0.4.10)
  Using cached aiohttp-middlewares-1.2.1.tar.gz (14 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting aiosignal>=1.1.2 (from aiohttp~=3.5->claude==0.4.10)
  Using cached aiosignal-1.3.1.tar.gz (19 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting attrs>=17.3.0 (from aiohttp~=3.5->claude==0.4.10)
  Using cached attrs-23.2.0.tar.gz (780 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting frozenlist>=1.1.1 (from aiohttp~=3.5->claude==0.4.10)
  Using cached frozenlist-1.4.1.tar.gz (37 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting multidict<7.0,>=4.5 (from aiohttp~=3.5->claude==0.4.10)
  Using cached multidict-6.0.5.tar.gz (59 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting yarl<2.0,>=1.0 (from aiohttp~=3.5->claude==0.4.10)
  Using cached yarl-1.9.4.tar.gz (141 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting async-timeout<5.0,>=4.0 (from aiohttp~=3.5->claude==0.4.10)
  Using cached async-timeout-4.0.3.tar.gz (8.3 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting voluptuous~=0.11 (from configpp~=0.3->claude==0.4.10)
  Using cached voluptuous-0.14.2.tar.gz (50 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting command-tree~=0.7 (from configpp~=0.3->claude==0.4.10)
  Using cached command-tree-0.7.1.tar.gz (15 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting python-slugify~=1.2 (from configpp~=0.3->claude==0.4.10)
  Using cached python-slugify-1.2.6.tar.gz (6.8 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting python-dateutil~=2.7 (from configpp~=0.3->claude==0.4.10)
  Using cached python-dateutil-2.8.2.tar.gz (357 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting ruamel.yaml~=0.15.44 (from configpp~=0.3->claude==0.4.10)
  Using cached ruamel.yaml-0.15.100.tar.gz (318 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting typing-inspect~=0.3 (from configpp~=0.3->claude==0.4.10)
  Using cached typing_inspect-0.9.0.tar.gz (13 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting PyYAML~=5.1 (from configpp~=0.3->claude==0.4.10)
  Using cached PyYAML-5.4.1.tar.gz (175 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [48 lines of output]
      running egg_info
      writing lib3/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib3/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/Users/trevorjohnson/claude-env/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/trevorjohnson/claude-env/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/trevorjohnson/claude-env/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/_g/3w9_rzvj3zs4r_qcz1qb0w5r0000gn/T/pip-build-env-7zcmxx7t/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/_g/3w9_rzvj3zs4r_qcz1qb0w5r0000gn/T/pip-build-env-7zcmxx7t/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/_g/3w9_rzvj3zs4r_qcz1qb0w5r0000gn/T/pip-build-env-7zcmxx7t/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 271, in <module>
        File "/private/var/folders/_g/3w9_rzvj3zs4r_qcz1qb0w5r0000gn/T/pip-build-env-7zcmxx7t/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/private/var/folders/_g/3w9_rzvj3zs4r_qcz1qb0w5r0000gn/T/pip-build-env-7zcmxx7t/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/private/var/folders/_g/3w9_rzvj3zs4r_qcz1qb0w5r0000gn/T/pip-build-env-7zcmxx7t/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/private/var/folders/_g/3w9_rzvj3zs4r_qcz1qb0w5r0000gn/T/pip-build-env-7zcmxx7t/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/_g/3w9_rzvj3zs4r_qcz1qb0w5r0000gn/T/pip-build-env-7zcmxx7t/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/private/var/folders/_g/3w9_rzvj3zs4r_qcz1qb0w5r0000gn/T/pip-build-env-7zcmxx7t/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/_g/3w9_rzvj3zs4r_qcz1qb0w5r0000gn/T/pip-build-env-7zcmxx7t/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 321, in run
          self.find_sources()
        File "/private/var/folders/_g/3w9_rzvj3zs4r_qcz1qb0w5r0000gn/T/pip-build-env-7zcmxx7t/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 329, in find_sources
          mm.run()
        File "/private/var/folders/_g/3w9_rzvj3zs4r_qcz1qb0w5r0000gn/T/pip-build-env-7zcmxx7t/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 551, in run
          self.add_defaults()
        File "/private/var/folders/_g/3w9_rzvj3zs4r_qcz1qb0w5r0000gn/T/pip-build-env-7zcmxx7t/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
          sdist.add_defaults(self)
        File "/private/var/folders/_g/3w9_rzvj3zs4r_qcz1qb0w5r0000gn/T/pip-build-env-7zcmxx7t/overlay/lib/python3.8/site-packages/setuptools/command/sdist.py", line 112, in add_defaults
          super().add_defaults()
        File "/private/var/folders/_g/3w9_rzvj3zs4r_qcz1qb0w5r0000gn/T/pip-build-env-7zcmxx7t/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "/private/var/folders/_g/3w9_rzvj3zs4r_qcz1qb0w5r0000gn/T/pip-build-env-7zcmxx7t/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
        File "<string>", line 201, in get_source_files
        File "/private/var/folders/_g/3w9_rzvj3zs4r_qcz1qb0w5r0000gn/T/pip-build-env-7zcmxx7t/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip. 

**Summary**:
Failing due to PyYAML requiring cython functionality during compile, attribute error suggests missing cython libs. Tried in fresh virtualenv, still seeing the issue.

**Ask**: Advice on resolving PyYAML M1 build issues?

**Comment by rattrayalex** [comment]
You want `pip install anthropic`, not `pip install claude`. This package does not depend on PyYAML.
