### ISSUE TITLE
ImportError: cannot import name 'ModelField' from 'pydantic.fields'

### ISSUE THREAD

**Issue by uripeled2** [anthropics/anthropic-sdk-python#49]
I am using python 3.9 and I install anthropic==0.3.1 and when I am running:
from anthropic import AsyncAnthropic
I am getting:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "venv/lib/python3.9/site-packages/anthropic/__init__.py", line 3, in <module>
    from . import types
  File "venv/lib/python3.9/site-packages/anthropic/types/__init__.py", line 5, in <module>
    from .completion import Completion as Completion
  File "venv/lib/python3.9/site-packages/anthropic/types/completion.py", line 3, in <module>
    from .._models import BaseModel
  File "venv/lib/python3.9/site-packages/anthropic/_models.py", line 11, in <module>
    from pydantic.fields import ModelField
ImportError: cannot import name 'ModelField' from 'pydantic.fields' (venv/lib/python3.9/site-packages/pydantic/fields.py)

**Comment by rattrayalex** [comment]
Fixed in v0.3.2
